# Generated by Django 5.2 on 2025-05-06 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='guest_id_pin',
            field=models.CharField(max_length=4, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='room',
            name='qr_code',
            field=models.URLField(blank=True, null=True),
        ),
    ]
