# Generated by Django 5.2 on 2025-05-07 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0004_roomserviceitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomserviceitem',
            name='category',
            field=models.CharField(choices=[('Starters', 'Starters'), ('Mains', 'Mains'), ('Desserts', 'Desserts'), ('Drinks', 'Drinks'), ('Others', 'Others')], default='Others', max_length=50),
        ),
    ]
