# Generated by Django 5.2 on 2025-05-10 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0006_order_orderitem_order_items'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='qr_code',
            new_name='in_room_breakfast_qr_code',
        ),
        migrations.AddField(
            model_name='room',
            name='kids_entertainment_qr_code',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='room_service_qr_code',
            field=models.URLField(blank=True, null=True),
        ),
    ]
