# Generated by Django 5.2 on 2025-05-10 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0008_breakfastitem_breakfastorder_breakfastorderitem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='breakfastitem',
            name='price',
        ),
    ]
