# Generated by Django 5.2 on 2025-05-05 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.IntegerField(unique=True)),
                ('is_occupied', models.BooleanField(default=False)),
                ('guests', models.ManyToManyField(blank=True, related_name='rooms', to='guest.guest')),
            ],
        ),
    ]
