# Generated by Django 5.2 on 2025-05-06 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_room_guest_id_pin_room_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='guest_id_pin',
            field=models.CharField(blank=True, max_length=4, null=True, unique=True),
        ),
    ]
