# Generated by Django 5.2 on 2025-05-07 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0003_alter_room_guest_id_pin'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomServiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('image', models.ImageField(blank=True, null=True, upload_to='room_service_items/')),
                ('description', models.TextField()),
            ],
        ),
    ]
