# Generated by Django 5.2 on 2025-05-10 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0007_rename_qr_code_room_in_room_breakfast_qr_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BreakfastItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('image', models.ImageField(blank=True, null=True, upload_to='breakfast_items/')),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('Mains', 'Mains'), ('Breads', 'Breads'), ('Drinks', 'Drinks'), ('Sides', 'Sides')], default='Mains', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='BreakfastOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.IntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BreakfastOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room.breakfastitem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room.breakfastorder')),
            ],
        ),
        migrations.AddField(
            model_name='breakfastorder',
            name='items',
            field=models.ManyToManyField(through='room.BreakfastOrderItem', to='room.breakfastitem'),
        ),
    ]
