# Generated by Django 5.2 on 2025-05-10 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0009_remove_breakfastitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='breakfastitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
